### ISSUE TITLE
Request To Prepare A documentation

### ISSUE THREAD

**Issue by servusdei** [gauthamp10/uploadfile-uploadindia#2]
A documentation on how to use with screenshots or video is better.And Also I don't know if this is working or not

**Comment by servusdei** [comment]
Well @gauthamp10 Dont want to Do That.
Closing

**Comment by gauthamp10** [comment]
The website itself is illegal and I don't want to loop upon uploadfile or upindia anymore. They have changed their codebase to client side download with key-generation.
